services:
  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_config:/config
      - caddy_data:/data
      - /repos/coach/vm/coach/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - homeassistant
      - nodered
      - nightscout
    restart: unless-stopped

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    ports:
      - "8123:8123"
    volumes:
      - ha_config:/config
    restart: unless-stopped

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    ports:
      - "1880:1880"
    env_file:
      - /repos/coach/vm/coach/docker/compose/nodered.env
    environment:
      - HA_BASE_URL=http://homeassistant:8123
      - HA_NOTIFY_SERVICE=notify.mobile_app_masterblaster
      # HA_TOKEN is provided via env_file (do not commit secrets)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1880"]
      interval: 30s
      timeout: 5s
      retries: 5
    volumes:
      - nodered_data:/data
    restart: unless-stopped

  nightscout-mongo:
    image: mongo:5
    container_name: nightscout-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - nightscout_mongo:/data/db
    restart: unless-stopped

  nightscout:
    image: nightscout/cgm-remote-monitor:latest
    container_name: nightscout
    depends_on:
      - nightscout-mongo
    ports:
      - "1337:1337"
    environment:
      - API_SECRET=CHANGE_THIS_very_secret_123
      - MONGO_CONNECTION=mongodb://root:example@nightscout-mongo:27017/nightscout?authSource=admin
      - INSECURE_USE_HTTP=true
      - DISPLAY_UNITS=mg/dl
      - TIMEZONE=America/Los_Angeles
      - PORT=1337
      - ENABLE=careportal basal iob rawbg
    restart: unless-stopped

volumes:
  caddy_config:
  caddy_data:
  ha_config:
  nodered_data:
  nightscout_mongo:
